apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: localhost:5432
    user: graph-node
    secureJsonData:
      password: let-me-in
    jsonData:
      database: graph-node
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false