[[ipfs]]
url = "http://host.docker.internal:5001"
client_type = "Cat"

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = ["default"]

[chains]
ingestor = "default"

[chains.mainnet]
shard = "primary"
provider = [
  { label = "erpc", url = "http://host.docker.internal:4444/main/evm/1", features = ["archive"] }
]
